version: 2
jobs:
  build:
    docker:
      - image: nixos/nix:1.11
    steps:
      - checkout
      - run:
          name: Setup
          command: .circleci/setup.sh
      - restore_cache:
          keys:
            - nix-{{ checksum "requirements.nix" }}-2
      - run:
          name: Build
          command: nix-build
      - run:
          name: Deploy
          command: nix-shell -p nodejs --run ".circleci/deploy.sh"
      - save_cache:
          key: nix-{{ checksum "requirements.nix" }}-3
          when: always
          paths:
            - /nix
