version: 2
jobs:
  build:
    docker:
      - image: nixos/nix:2.1.1
    steps:
      - checkout
      - run: git submodule sync
      - run: git submodule update --init
      - run:
          name: Setup
          command: .circleci/setup.sh
      - restore_cache:
          keys:
            - nix-{{ checksum "requirements.nix" }}-4
      - run:
          name: Build
          command: nix-build
      - run:
          name: Deploy
          command: nix-shell --run ".circleci/deploy.sh"
      - save_cache:
          key: nix-{{ checksum "requirements.nix" }}-4
          when: on_success
          paths:
            - /nix
